### ISSUE TITLE
ES6 Modules version

### ISSUE THREAD

**Issue by brettz9** [WebReflection/tressa#4] opened 2018-09-26 14:58 UTC
Might you be open to releasing an ES6 Modules version?

**Comment by WebReflection** [comment] 2018-09-26 15:02
only when it'll be needed. This is a NodeJS only module.

**Comment by WebReflection** [comment] 2018-09-26 15:03
sorry for rushing out ... also this is duplicate of #3

**Closed as completed by WebReflection** 2018-09-26 15:02 UTC

**Comment by brettz9** [comment] 2018-09-27 03:27
How is this a NodeJS-only module? You explicitly support the browser... Would you be open to a PR using Rollup (also for `consolemd`)?

**Comment by WebReflection** [comment] 2018-09-27 08:10
> How is this a NodeJS-only module?

it's technically not but I use it only with nodejs 😅
